### PR TITLE
Add makefiles to build with bitbake

### PR DESCRIPTION
**Pull request by Taapat**
If it does not allow build to you, then maybe they can be added in a separate branch.
But in that case, this branch also need regular updating.

### CODE REVIEW

**Comment by e2iplayer** [comment]
Do you want make exteplayer3 to depend from libexteplayer3.so?

**Comment by Taapat** [comment]
Yes I build binary exteplayer3 witch depend from libexteplayer3.so, and library libexteplayer3.so.
This allow use library libexteplayer3.so without binary.

**Comment by e2iplayer** [comment]
It has no sens. exteplayer3 != libeplayer3.so. We use fact that this is separete process.
Using libexteplayer3 with E2 make it unstable. We use exit inside your libexteplayer3.

With E2 it will couse to close wole prosess. It is not what we want.

**Comment by e2iplayer** [comment]
If you want to use it directly with E2 you should use method @mx3L:
http://forums.openpli.org/topic/41198-serviceapp-gstplayer-and-exteplayer3/

Then it will work stable. Otherwise, there it will not works stable.

**Comment by Taapat** [comment]
The fact that the binary file are separated from the library no effect on stability.
Allow users to choose what they want to do.

Currently I use mx3L serviceapp, but I do not think it is right to use additional two binary files + python to use the library.
This increases stability but causes so much unnecessary code.

**Comment by e2iplayer** [comment]
"The fact that the binary file are separated from the library no effect on stability."
You are wrong. What happen when you call exit(-1) inside the library which is using by 
E2?

And what happen when you call many time playback (without closing process) and some resource will be not free?
The same what happen when ffmpeg will crash? And so, on.

When you use separete process all resources will be free by system each time when it will be closed.
The same with crashes or hangs up. Already I wrote about it I will not repeat here.

Do you know why google Chrome run each site/tab in separate process? No in separate thread?
Yes due to stability .

Stability is the most important for users.

**Comment by Taapat** [comment]
I am in my makefiles split the libexteplayer library from exteplayer binary file.
This is about what I wrote: "The fact that the binary file are separated from the library no effect on stability."
These makefiles do not affect how the library is used after.

If there are errors while working, then it need to fix, rather than creating a workoraund with separate  process.

**Comment by e2iplayer** [comment]
Ok. You know better, so lets go to the users and say them after 2 yers when you fix all. OK?

You know everything better, but it is the fact that extepalyer3 in IPTVPlayer works very stable.
It was tested by hundreds of users.

E2 system player based on libeplayer NOT WORKING STABLE. Especially on bad streams or expired links. 
"If there are errors while working, then it need to fix, rather than creating a workoraund with separate process."
So, why you not fix it? Why you not fix ffmpeg libs which can crash when data in stream are wrong and so on. 

And also lets go to google and say them that they know nothing.
OK?

Because you write nonsense. This is not "workoraund" this is architecture which gives better stability.

Did you read about Hurd - Gnu operation system?

**Comment by e2iplayer** [comment]
By the design, this project was to create stable player running in separate process.
If you not like this premise then sorry but there is no place to discussion.

As you wrote some were that you are working on libeplayer solution for MIPS, so simple please continue work. 

But you must know that even SH4 users complain about libeplayer stability for IP streams.

And once again exteplayer3 != libeplayer.

OK?

**Comment by Taapat** [comment]
I do not want to discuss with you if you're not open for discussion.

Please explain how this division negatively affects libexteplayer itself and close the pull request, or accept it, or ignore.

OK?

**Comment by e2iplayer** [comment]
Exteplayer3 is intended as player which run as separate process.

Separate part of it code to dynamic SO library does not make sense and would cause problems with developing.
At now on the same STB we can use as many versions of exteplayer3 as we want.

Run player as a separate process is an architecture.

Back to the old technology is not a case.

**Comment by Taapat** [comment]
So your message to all is:
Exteplayer3 is very unstable and with a lot of bugs.
It is not suitable for normal media play.
The only way to use it is as a separate process because only in that case it will not cause problems.

I think it's very strange, but ok, I accept your point of view and more not bother you with my pull requests.

**Comment by mx3L** [comment]
@Taapat 
I think that extra code is worth it, it adds extra indirection which adds stability and flexibility. 

As was already said stability is provided by always exiting process, so OS will release all resources, so also resources which by our or ffmpeg mistake were allocated on the heap and not freed -> no memory leaks. If we leave it like it is uptime of enigma2 will be cut down by accumulated memory leaks.  Next thing is that if for some reason process crashes it will not bring down enigma2 with it.
It's also possible to kill process if for some reason is player frozen, while in enigma2 we would have only endless spinner(as you know this is sometimes the case with gstreamer, in order to fix this issues, you really have to dig deep in gstreamer source to find a solution)

Flexibility means that enigma2 is not tied to gstreamer/ffmpeg framework, it doesn't need to know how it's playback done, there needs to be defined only clear interface between player and enigma2. It also speeds up development, since you don't have to rebuild whole enigma2 in order to test changes, you can even switch binary at runtime of enigma2.

>  Currently I use mx3L serviceapp, but I do not think it is right to use additional two binary files + python to use the library.

No python plugin is neccessary it can be added directly to enigma2, I just did it this way so anybody can test it by just installing plugin and not patching enigma2.

Why is it not good to use additional binaries? Can you tell us why is approach of using libexteplayer directly in enigma2 better?

**Comment by Taapat** [comment]
Please show me where I in this pull request ask use exteplayer in enigma2.

I logically split library separately from the binary file which designed to manage this library from the command line.
Just as it is implemented for example in ffmeg. Libraries separately and ffmpeg binary file separately.

Yes, it allows the use of the library directly in the enigma, but it does not do it mandatory.

As I wrote, maybe you need to allow users to choose what they want to do, rather than impose your views.
But I understand that you can never accept the fact that someone can do something different, so I better not do anything.

**Comment by mx3L** [comment]
> Please show me where I in this pull request ask use exteplayer in enigma2.

Fair enough, my mistake, I just make an assumption.

> I logically split library separately from the binary file which designed to manage this library from the command line.
> Just as it is implemented for example in ffmeg. Libraries separately and ffmpeg binary file separately

I personally don't have problem with this, but clearly @samsamsam's intention of this code was to use it as only one file binary, therefore there are things which shouldn't be there, for example exit calls. Of course that's easily solvable.

> As I wrote, maybe you need to allow users to choose what they want to do, rather than impose your views.

I'm just stating my opinion that using exteplayer in separate process has it's benefits. And was interested why would you want to use it another way, that's all.

> But I understand that you can never accept the fact that someone can do something different, so I better not do anything.

I re-read my post and I'm not sure what are you talking about, where did I say or imply this?

I don't have much to say in this, but I would be glad if you could join us and contribute.

**Comment by Taapat** [comment]
> I personally don't have problem with this, but clearly @samsamsam's intention of this code was to use it as only one file binary

Yes, but as I understand @samsamsam not used bitbake. Therefore, it could not influence him.

> I re-read my post and I'm not sure what are you talking about, where did I say or imply this?

I wrote this about @samsamsam.
If for every commit I have fought this fight, then it is not necessary for anyone, especially for me.
I can accept the technical arguments, but I can not accept such emotions from @samsamsam.
He wrote so much is redundant, not related to this commit, that even you are missing content of this commit.

**Comment by mx3L** [comment]
> Yes, but as I understand @samsamsam not used bitbake. Therefore, it could not influence him.

Actually as you proposed this, we were discussing bitbake recipe but only for creating single binary, it's created and ready to be pushed.

Note @samsamsam has a point, now it's possible to have more independent binaries, but if we used what you're suggesting, they would all depend on library.

So maybe allow possibility to have it both ways, to have bitbake recipe for single binary which wouldn't depend on library and to have bitbake only for library?(As it was done for librtmp and rtmpdump recipes). What do you think guys?

Also you don't need to add makefiles in order to build library or single binary by bitbake.

**Comment by e2iplayer** [comment]
@Taapat 
You have technical arguments? No. You do not have. 
You not answered to my arguments.

@mx3L as I understand @Taapat he want to make similar solution as it is SH4.
This solution does not works stable and this is the reason why external players was created. 
This is the clue.

There is no reason to separate part of the code to make shared library for such small project
The only reason why @Taapat  want to do this is because he want to make such unstable solution as I understand. Otherwise why E2 is not splitted to manny difference libs? Maybe we need to put each function in separate lib?

To use this code as separate lib there will be need to make changes this is not what should be done.
Another changes another ifdef's and, so on. 
In my opinion it is waist of time and the solution will be still unstable.

So really this is what you want?

**Comment by mx3L** [comment]
@samsamsam 
As you know I do not share @Taapat's vision to use exteplayer as library.

I just thought, that as long as @Taapat help us to improve code, then let him do it. **IF** it doesn't have negative impact on what we are doing and it's clearly stated that we encourage to use this as only single binary solution, since using it as library will be probably unstable.

But if it is as you say, that it will also add a lot of unnecessary code, then I guess it's probably not worth it.

**Comment by Taapat** [comment]
@mx3L As I wrote, in this moment I am using your serviceapp.
Therefore, at this moment for my do not important to distribute seperate libraries from binary file.
Just it seems to me, that this is logical.

But instead to hear the technical arguments as a separate library disturb him, I read a lot of spam with @samsamsam emotions.
It is enough for me to understand that I can not cooperate with such a person.

My knowledge in C++ are very low. I also have little knowledge about media.
If I'm not doing anything here, it will not be a big loss for you.

If I decide to do something, then you can always use useful for you from my git.

**Comment by e2iplayer** [comment]
@Taapat
You really do not see arguments? 
No? Really?

This is very strange because I give you many of them. 
I think that good thing is to read why and when the SO library is good choice.

You can separate each function as separate SO lib. But this is not good idea.
Share library is create to share it beetween at least two diffrent programs. 

I which programs do you want to use it?
So, to make clear I gave you arguments. So, why you are such nonsense: "But instead to hear the technical arguments as a separate library disturb him, I read a lot of spam with @samsamsam emotions.".

Which of my words to you were the spam?

And one more clarification: @Taapat come here and say something like that: "OK maybe this is working stable but it is not good to use it in this way. The better choice is to use in old unstable manner because we should give users choice". 
What choice? Between stable and unstable?
And also"if this code is not safe to use as library then it should be fixed". Really? 

At now @Taapat start to complain. 

This is all very strange. So, when you say about arguments you should give argument why old, not stable manner is better from the new one stable.

Because I gave you the arguments for example: "
- it is not safe to use this code as shared library be E2, 
- separate process is not "workaround" this is architecture which gives better stability.
- running part of code as separate process is nothing new there is manny project which use split parts of functionalities and run them as separate processes
- the result binary is very small due to this using SO lib has no sens 
- there is more difficult to use many different versions at the same time on the same system (it is possible but more difficult)

You really do not see arguments?

**Pull request closed without merging**
